import route from './router.js';
import Home from '/imports/ui/Home.jsx';
import ContactUs from '/imports/ui/ContactUs.jsx';
import {About} from '/imports/ui/About.jsx';
import {Painting} from '/imports/ui/Painting.jsx';
import {Sculpture} from '/imports/ui/Sculpture.jsx';
import {Drawing} from '/imports/ui/Drawing.jsx';
import {Craft} from '/imports/ui/Craft.jsx';
import ArtSignUp from '/imports/ui/invisNavBar/ArtSignUp.jsx';
import LogIn from '/imports/ui/invisNavBar/LogIn.jsx';
import { Pops } from  '/imports/ui/Pops.jsx';
import { Paul } from '/imports/ui/Paul.jsx';
import {Titans} from '/imports/ui/Titans.jsx';
import { Pierre } from '/imports/ui/Pierre.jsx';
import {Claude} from '/imports/ui/Claude.jsx';
import { Diego } from '/imports/ui/Diego.jsx';
import { Edvard } from '/imports/ui/Edvard.jsx';
import { Vincent } from '/imports/ui/Vincent.jsx';
import { Raphael } from '/imports/ui/Raphael.jsx';
import { Newartist }  from '/imports/ui/Newartist.jsx';
import {Buy1} from '/imports/ui/Buy1.jsx';
import {Buy2} from '/imports/ui/Buy2.jsx';
import {Buy3} from '/imports/ui/Buy3.jsx';
import {Buy4} from '/imports/ui/Buy4.jsx';
import {Buy5} from '/imports/ui/Buy5.jsx';
import {Buy6} from '/imports/ui/Buy6.jsx';
import {Buy7} from '/imports/ui/Buy7.jsx';
import {Buy8} from '/imports/ui/Buy8.jsx';
import {Buy9} from '/imports/ui/Buy9.jsx';
import {Buy10} from '/imports/ui/Buy10.jsx';
import {Buy11} from '/imports/ui/Buy11.jsx';
import {Buy12} from '/imports/ui/Buy12.jsx';
import {Scul1} from '/imports/ui/Scul1.jsx';
import {Scul2} from '/imports/ui/Scul2.jsx';
import {Scul3} from '/imports/ui/Scul3.jsx';
import {Scul4} from '/imports/ui/Scul4.jsx';
import {Scul5} from '/imports/ui/Scul5.jsx';
import {Scul6} from '/imports/ui/Scul6.jsx';
import {Scul7} from '/imports/ui/Scul7.jsx';
import {Scul8} from '/imports/ui/Scul8.jsx';
import {Scul9} from '/imports/ui/Scul9.jsx';
import {Scul10} from '/imports/ui/Scul10.jsx';
import {Scul11} from '/imports/ui/Scul11.jsx';
import {Scul12} from '/imports/ui/Scul12.jsx';
import {Draw1} from '/imports/ui/Draw1.jsx';
import {Draw2} from '/imports/ui/Draw2.jsx';
import {Draw3} from '/imports/ui/Draw3.jsx';
import {Draw4} from '/imports/ui/Draw4.jsx';
import {Draw5} from '/imports/ui/Draw5.jsx';
import {Draw6} from '/imports/ui/Draw6.jsx';
import {Draw7} from '/imports/ui/Draw7.jsx';
import {Draw8} from '/imports/ui/Draw8.jsx';
import {Draw9} from '/imports/ui/Draw9.jsx';
import {Draw10} from '/imports/ui/Draw10.jsx';
import {Draw11} from '/imports/ui/Draw11.jsx';
import {Draw12} from '/imports/ui/Draw12.jsx';










route('/', Home);
route('/contact', ContactUs);
route('/about', About);
route('/painting', Painting);
route('/sculpture', Sculpture);
route('/drawing', Drawing);
route('/craft', Craft);
route('/SignUp', ArtSignUp);
route('/LogIn', LogIn);
route('/Pops', Pops);
route('/paul', Paul);
route('/titans', Titans);
route('/Pierre', Pierre);
route('/newartist', Newartist );
route('/vincent', Vincent);
route('/raphael', Raphael);
route('/edvard', Edvard);
route('/claude', Claude);
route('/diego', Diego);
route('/buy1', Buy1);
route('/buy2', Buy2);
route('/buy3', Buy3);
route('/buy4', Buy4);
route('/buy5', Buy5);
route('/buy6', Buy6);
route('/buy7', Buy7);
route('/buy8', Buy8);
route('/buy9', Buy9);
route('/buy10', Buy10);
route('/buy11', Buy11);
route('/buy12', Buy12);
route('/scul1', Scul1);
route('/scul2', Scul2);
route('/scul3', Scul3);
route('/scul4', Scul4);
route('/scul5', Scul5);
route('/scul6', Scul6);
route('/scul7', Scul7);
route('/scul8', Scul8);
route('/scul9', Scul9);
route('/scul10', Scul10);
route('/scul11', Scul11);
route('/scul12', Scul12);
route('/draw1', Draw1);
route('/draw2', Draw2);
route('/draw3', Draw3);
route('/draw4', Draw4);
route('/draw5', Draw5);
route('/draw6', Draw6);
route('/draw7', Draw7);
route('/draw8', Draw8);
route('/draw9', Draw9);
route('/draw10', Draw10);
route('/draw11', Draw11);
route('/draw12', Draw12);